.\"
.\" $Id$
.\" $Revision$
.\"
.\" mkconfig.7
.\"
.\" Copyright 2010 Brad Lanam  Walnut Creek CA USA
.\"
.\" bll6969di_at_gmail.com
.\"
.TH mkconfig 7 "12 May 2010"
.SH Name
mkconfig \- build configuration utilities
.SH Synopsis
.\" mkconfig.sh [-C] [-c <cache-file>]
.\"       [-l <log-file>] config-file
.\" mkreqlib.sh [-c <cache-file>] [-o <output-file>] config-file
.\" runtests.sh <tests-dir> [test1, ...]
.B mkconfig.sh
[\fB\-C\fP]
[\fB\-c\fP <cache\-file>]
[\fB\-l\fP <log\-file>]
config-file
.PP
The \-C option clears any cache file before processing the units.
.PP
cache\-file defaults to 'mkconfig.cache'.
.PP
log\-file defaults to 'mkconfig.log'.
.PP
config\-file is a file containing a list of configuration commands.
.PP
.B mkreqlib.sh
[\fB\-c\fP <cache\-file>]
[\fB\-o\fP <output\-file>]
input\-file
.PP
cache\-file defaults to 'mkconfig.cache'.
.PP
output\-file defaults to 'reqlibs.txt'.
.PP
input\-file is the C/C++ output\-file created by mkconfig.sh.
.PP
.B runtests.sh
tests\-dir
[test1, ...]
.PP
tests\-dir is a directory containing test scripts.
.PP
The tests to be run may be specified on the command line.
.SH Description
\fImkconfig.sh\fP
is a build configuration utility.
It is written in portable shell script and
designed to be extensible for any configuration use.  Most Bourne
Shell compatible shells will work.  \fImkconfig.sh\fP will choose
\fIksh\fP, \fIash\fP or \fIdash\fP over \fIbash\fP since they are
faster.
.PP
\fImkconfig.sh\fP
is intended to generate a file that can be used as an included file,
a shell script, a configuration file, or any other use.
.PP
\fImkreqlib.sh\fP
is used in conjunction with the c\-main language unit to output the
libraries required for linking.  See the description for the 'lib'
check routine for the c\-main language unit below.
.PP
\fIruntests.sh\fP
is a simple test harness for mkconfig.
.SH Basic Configuration Commands (mkconfig.sh)
.TP
\fB#\fP comment
.br
Comments begin with a '#' in column 1.  Blank lines are ignored.
.TP
\fBoutput\fP file\-name (required)
.br
Specify the name of the output file.
.TP
\fBloadunit\fP unit\-name
.br
Include a mkconfig unit for testing.
Units may include specific check routines that may be performed.
.TP
\fBstandard\fP
.br
Perform any standard checks for the language unit that was loaded.
.TP
\fBcommand\fP name\-of\-command
.br
Check if command exists in the path.
e.g.: command sed
.TP
.B include endinclude
.br
Include all of the code between these two tags
in the output file.  Backslashes must
be escaped with a backslash.
.PP
Other commands depend on the units loaded.
.SH Environment Units
The environment units create an output file that can be used
as shell script input to set your environment.
.TP
.B env-systype
.br
The systype environment unit determines what type, revision and
architecture of the system you are running on.
.RS
.TP
\fBsystem\fP {type|rev|arch}
.br
The type, rev and arch commands will create
the _MKCONFIG_SYSTYPE, _MKCONFIG_SYSREV, and _MKCONFIG_SYSARCH
environment variables respectively.  These
correspond to the output of uname -s, uname -r and uname -m.
On AIX, the oslevel command is used to attempt to resolve the revision
of the operating system.  On MacOSX, the revision is currently unchanged and
does not correspond to the marketing version.
.RE
.PP
.TP
.B env-cflags
.br
The cflags environment unit determines basic flags needed to run the
C compiler.  Since these units are interdependent on each other, they
should be configured in the order: cc, using_gcc, cflags, ldflags, and libs.
.RS
.TP
\fBcc\fP
.br
Determines the C compiler being used (default cc).
Sets the CC environment variable.
.TP
\fBusing_gcc\fP
.br
Sets the _MKCONFIG_USING_GCC environment variable to 'Y' if the gcc
compiler is being used.
.TP
\fBcflags\fP
.br
Sets the CFLAGS environment variable according to the 'getconf' program
and appropriate to the operating system and compiler.
.TP
\fBldflags\fP
.br
Sets the LDFLAGS environment variable according to the 'getconf' program
and appropriate to the operating system and compiler.
.TP
\fBlibs\fP
.br
Sets the LIBS environment variable according to the 'getconf' program
and appropriate to the operating system and compiler.
.RE
.TP
.B env-extension
.RS
.TP
\fBextension\fP {obj|exe}
.br
The obj and exe arguments correspond to the OBJ_EXT and EXE_EXT
environment variables. These two variables are set to the
object file extension (.o, .obj) and executable file
extension (none or .exe) per the operating system and compiler.
.RE
.TP
.B env-msgfmt
.RS
.TP
\fBcmd_msgfmt\fP
.br
Sets the XMSGFMT environment variable to the path of the
msgfmt or gmsgfmt command, if any.
.RE
.SH C Language Units
.TP
.B c\-main
.br
The c\-main unit creates an include file for C programs.
The \fIhdr\fP and \fIsys\fP directives should be listed first
in the configuration file so that the headers are
available for use in the other tests.
.RS
.TP
\fBstandard\fP
.br
The \fIstandard\fP checks are for: the headers stdio.h, stdlib.h, sys/types.h
and sys/param.h, the keywords \fIvoid\fP and \fIconst\fP,
and C function prototypes.
.TP
\fBhdr\fP name\-of\-header [required\-headers]
.br
Check for a header.
The standard include path as set in CFLAGS is used.
If \fIrequired\-headers\fP is specified, those headers
are included in the compilation test before attempting
the compilation test.
e.g. hdr storage/volumes.h gui/window.h
.TP
\fBsys\fP name\-of\-sys\-header [required\-headers]
.br
Like \fIhdr\fP, but looks in the sys/ directory.
e.g. sys types.h
.TP
\fBclass\fP class [libs]
.br
Check to see if class \fIclass\fP exists.
If the optional \fIlibs\fP are specified,
the test will try first without the libraries, then with
the first set of libraries specified, then the next set, etc.
Sets of libraries to be tested are separated by commas.
e.g.: class os::Volumes
.RS
.PP
Execute \fImkreqlib.sh\fP after creating the configuration file
to output the libraries required for linking.  See the usage for
\fImkreqlib.sh\fP in the lib check below.
.RE
.TP
\fBconst\fP constant\-name [required\-headers]
.br
Check to see that a constant exists.
If \fIrequired\-headers\fP is specified, those headers
are included in the compilation test before attempting
the compilation test.
e.g. const O_RDONLY
.TP
\fBdcl\fP {int|ptr} variable
.br
Check to see if the variable is declared.
If \fIint\fP is specified, the variable is a numeric type.
If \fIptr\fP is specified, the variable is a pointer type.
e.g. dcl int errno; dcl ptr optarg
.TP
\fBkey\fP keyword
.br
Check to see if a C-language keyword is reserved.
e.g. key volatile
.TP
\fBlib\fP function [libs, ...]
.br
Check to see if library function \fIfunction\fP exists.
If the optional \fIlibs\fP are specified,
the test will try first without the libraries, then with
the first set of libraries specified, then the next set, etc.
Sets of libraries to be tested are separated by commas.
e.g. lib gettext -lintl, -lintl -liconv
will first test gettext, then gettext -lintl, then gettext -lintl -liconv.
.RS
.PP
Execute \fImkreqlib.sh\fP after creating the configuration file
to output the libraries required for linking.
.PP
\fImkreqlib.sh\fP creates the list of libraries required for linking
based on the configuration file.  This allows the user to modify
the configuration file and only the necessary libraries will be
linked in.
.PP
\fImkreqlib.sh\fP is executed with a command line argument of the
configuration file name.  The output file defaults to 'reqlibs.txt',
but may be changed with the \-o command line option.
.PP
The string '_dollar_', if included in the library function name
will be replaced with the '$' symbol.
.RE
.TP
\fBmember\fP struct member
.br
Check to see if \fImember\fP is a member of \fIstruct\fP.
e.g.: member statfs f_bsize
.TP
\fBnpt\fP function [library\-requirement]
.br
Check to see if if \fIfunction\fP needs to have a prototype declared.
The optional \fIlibrary\-requirement\fP should be written
as: _lib_<funcname>.
If \fIlibrary\-requirement\fP does not exist, _npt_<function>
will be set to false in the output file.
e.g. npt getopt; npt statfs _lib_statfs
.TP
\fBtyp\fP type\-name
.br
Check to see if type\-name exists.
e.g. typ size_t
.RE
.TP
.B c-statfs\-args
.RS
.TP
\fBstatfs_args\fP
.br
Checks to see how many arguments the statfs() system call accepts.
.RE
.TP
.B c-setmntent\-args
.RS
.TP
\fBsetmentent_args\fP
.br
Check to see how many arguments the setmntent() system call accepts.
.RE
.TP
.B c-include\-time
.RS
.TP
\fBinclude_time\fP
.br
Check to see if there is a conflict between time.h and sys/times.h.
.RE
.SH Tests (runtests.sh)
The test directory contains shell scripts that are executed
by \fIruntests.sh\fP.  If a 'test_order' file exists in the test
directory, it indicates the order the tests are run in.  The 'test_order'
file consists of a pass number followed by the test name (no trailing .sh).
If the 'test_order' file exists, only those tests in the file will be run.
.SH Writing a mkconfig Unit (mkconfig.sh)
To be completed.
.SH Environment Variables (mkconfig.sh)
_MKCONFIG_DIR - The directory where mkconfig.sh is installed.
.SH File Descriptors (mkconfig.sh)
The file descriptors are allocated as follows:
.br
9 - The mkconfig log file
.br
8 - Used by mkconfig.sh; not available for mkconfig unit scripts.
.br
7 - Used by mkconfig.sh; not available for mkconfig unit scripts.
.br
6 - Used by c-main.sh; not available for c language unit scripts.
.SH Writing a test script (runtests.sh)
To be completed.
.SH Environment Variables (runtests.sh)
.TP
_MKCONFIG_DIR
.br
The directory where mkconfig.sh is installed.
.TP
_MKCONFIG_RUNTOPDIR
.br
The original directory where the tests were started.
.TP
_MKCONFIG_RUNTSTDIR
.br
The directory containing the test scripts and associated
files.
.TP
_MKCONFIG_RUNTMPDIR
.br
The top level temporary directory.  Sub\-directories
are created for each test that is run.
.TP
_MKCONFIG_TSTRUNTMPDIR
.br
The temporary directory in which the test is run.
.TP
shelllist
.br
A list of valid shells installed on the system.
.SH See Also
iffe(1) autoconf(1) dist(7)
.SH Bugs
Send bug reports to: bll6969di_at_gmail.com
.SH Website
\fImkconfig\fP is currently packaged in conjunction with \fIdi\fP
.PP
http://www.gentoo.com/di/
.SH Author
This program is Copyright 2010 by Brad Lanam, Walnut Creek CA
.PP
Brad Lanam, Walnut Creek, CA (bll6969di_at_gmail.com)
